Game logic
adaorachi/tic-tac-toe pull request #3
Opened 2019-10-30 20:00 UTC by kazumaki

In this part of the project, we get rid of the classes from main.rb and created separated files for each class on the project. Removing all puts and gets from class methods and placing it into main.rb.

2019-10-31 21:59 UTC, maelfosso requested changes
# Changes required

Hello @adaorachi @kazumaki 

Nice work for a first try :clap: However there are some changes that you should do

- We must run the game by only typing **bin/main.rb**. But It's not working in your case. Make the **bin/main.rb executable**

- **attr_accessor** is not allowed. You should decide between **attr_reader** and **attr_writer**

- There are a lot of **sleep** in your code. It's not really needed.

- Define method instead of write too many code. Read suggestions I left below.

Kindly read the comments below and make the changes then submit a new code review request.
Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-10-31 21:59 UTC, maelfosso commented on lib/player.rb
> +  end
Just define it as a static method 
```ruby
class Player
    ...
    def self.random_player(*args)
        args.shuffle
    end
end
```
You could them call it like
```ruby
Player.random_player(@player1, @player2)
```

2019-10-31 21:59 UTC, maelfosso commented on lib/player.rb
> +  end
**attr_accessor** is not allowed

2019-10-31 21:59 UTC, maelfosso commented on lib/player.rb
> +  end
No need to use `attr_accessor`, you could initialize the player with the name and the marker directly
```ruby
def initialize(name, marker)
    ....
end
```

2019-10-31 21:59 UTC, maelfosso commented on bin/main.rb
>      player_second.marker = player_first.marker == 'X' ? 'O' : 'X'
You can initialize the players with both the **name** and the **marker**

2019-10-31 21:59 UTC, maelfosso commented on bin/main.rb
>      player_second.marker = player_first.marker == 'X' ? 'O' : 'X'
Instead of character `'X' / 'O'` use symbols **:X / :O**

2019-10-31 21:59 UTC, maelfosso commented on bin/main.rb
>    end
Split it in many methods 
- method for checking whether or not the position is valid or not
- method for looking for the good cell
- method for setting a marker in the read position

Define each of the 3 methods into the **Board** class

2019-10-31 21:59 UTC, maelfosso commented on lib/board.rb
> +  attr_accessor :cell_grid, :available
Why those two variables ? 
I think you could do the same what you want with only one property

2019-10-31 21:59 UTC, maelfosso commented on lib/board.rb
> +  end
Define a method to check if 3 consecutive cells are equal
```ruby
def all_equals?(cells, marker)
   [cells[0], cells[1], cells[2]].all? { |x| == marker }
end
```
and call it like this
```ruby
col1 = all_equals?([@available[0], @available[3], @available[6]], :X)
```
and so on

2019-10-31 21:59 UTC, maelfosso commented on lib/cell.rb
> +end
Please, are you sure that you can't work without that class ?

2019-11-01 16:15 UTC, adaorachi commented on lib/player.rb
> +  end
Hi @maelfosso. 
I don't think we can set the name and marker directly to the player class.
This is how our game is played. We choose a player at random to start the game. That player gets to choose a marker while the other marker is assigned to the other player automatically. The same player also gets to be the first to choose a position. 
We need to read and write the method marker to be able to use it.

2019-11-01 16:45 UTC, adaorachi commented on lib/board.rb
> +  attr_accessor :cell_grid, :available
We will need both methods to work with. One shows the available cells where a player can place his/her marker numbering from 1 to 9. The other shows the game board where the x and o are inputted.

2019-11-01 17:06 UTC, maelfosso commented on lib/player.rb
> +  end
I understand the direction you decide to take. You can keep it, but please change by adding the players as attribute of Board

**`OPTIONAL`**
IT's still possible to initialize the Player with both the name and his corresponding marker
```ruby
# read the player's name
name1 = gets.chomp
name2 = gets.chomp

# Shuffle 
random = Players.random_player([name1, name2])

# Define markers for each player
marker1 = random[0] == name1 ? :X : :O 
marker2 = random[0] == name2 ? :O : :X 

# Initialize the game with all the elements
board = Board.new(name1, name2, marker1, marker2, ...)
```
The Board
```ruby
def initialize(name1, name2, marker1, marker2....)
   @player1 = Player.new(name1, marker1)
   @player2 = Player.new(name2, marker2)
   @board = Board.new
end
```

2019-11-02 20:51 UTC, mcrd25 requested changes
# Changes required 🤓 

Hi @kazumaki and @adaorachi 👋,

Great job guys! I really like the effort put in! 👏 😄 

However, there are some changes to address! Please address them and submit another review.

Your game works perfectly 💯 but how you've implemented it could do with improvements so that you can meet the standard required by top ruby developers! 🙂 

For instance:
- Should avoid having input and output statements within classes 
- classes should be in a separate folder (NOT WITHIN YOUR SCRIPT FILE! lol 😛 )

### Required Changes
- Address all comments not marked by [OPTIONAL]
- You `Game` class should be in `lib` folder
- Remove all `puts` and `gets` calls from your class methods.
- Your linter is not passing all tests please address all linting issues referenced by stickler
Once you address my review comments I see no reason why you should not get the 👍! 

Your project was really unique and awesome! And I loved it!

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya Douglas](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2019-11-02 20:51 UTC, mcrd25 commented on bin/main.rb
> +class Game
All classes are to be kept in lib folder

2019-11-02 20:51 UTC, mcrd25 commented on bin/main.rb
> +    puts "Available      TIC-TAC_TOE\nmoves\n\n"
Return the board to draw then call the method in main.rb and output it like:
`puts draw_board`

This way when you move your `Game` class to lib folder you won't have the unwanted puts statements

2019-11-02 20:51 UTC, mcrd25 commented on bin/main.rb
> +    puts "#{row[6]} | #{row[7]} | #{row[8]}       #{available[6]} | #{available[7]} | #{available[8]}"
**Note: you must remove these put statements but how you do it is entirely up to you, hence the [OPTIONAL] ag**
[OPTIONAL]
Something like 
```ruby
"Available      TIC-TAC_TOE\nmoves\n\n\n
#{row[0]} | #{row[1]} | #{row[2]}       #{available[0]} | #{available[1]} | #{available[2]}\n
---------       --------- \n
#{row[3]} | #{row[4]} | #{row[5]}       #{available[3]} | #{available[4]} | #{available[5]}\n
---------       --------- \n
#{row[6]} | #{row[7]} | #{row[8]}       #{available[6]} | #{available[7]} | #{available[8]}
"
```
would also work. You'd return it and simply `puts @game.draw_board` or similar

2019-11-02 20:51 UTC, mcrd25 commented on bin/main.rb
> +      puts "Congratulations #{player.name.capitalize} wins!"
Try and do without any puts statement in your class methods.

So either you can break up methods (this one definitely needs to be broken up) and have them do smaller things and/or rearrange so that you are outputting and getting input from main

2022-06-21 14:11 UTC, closed without merging